/* cov40: what does a REALIZABLE data dispatch buy over the branchless ceiling of 34?
 *
 * Architecture modelled (see docs/attempts/2026-08-10-claude-cov40.md):
 *   IN                      A = b
 *   save/restore via two CRAZYs with an all-ones word (m1 is an involution)
 *                           A = b, mem[r] = b        (b survives)
 *   two CRAZY layers        A = v(b) = sum_i h_i(trit_i(b)) * 3^i,  h_i in M_2
 *   MOVD                    D = v+1                  <-- the branch
 *   k CRAZY layers          out = crazy^k(b, mem[v+1..v+k])
 *
 * The dispatch value v is a positionwise function of b, so the realizable class
 * partitions are exactly the product partitions: pick positions S, class(b) =
 * (h_i(trit_i(b)))_{i in S}.  Per class the tail is an independent member of the
 * depth-k straight-line family.
 *
 * This program computes, for every such partition, the SUM over classes of the
 * per-class maximum of the straight-line family.  That is an upper bound on the
 * whole architecture: it grants each class its own maps and its own constant,
 * ignores every layout/build cost, and ignores the fact that consecutive classes
 * share table cells.
 *
 * Two map sets are reported:
 *   FULL  the 15-element monoid generated by M0,M1,M2 with K free over all 256
 *         (an upper bound for ANY depth, so a genuine ceiling)
 *   M2    the 8-element depth-2 set with K restricted to what depth-2 high-trit
 *         maps can make (what a two-layer tail can actually do)
 */
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

static const int M[3][3] = {{1,0,0},{1,0,2},{2,2,1}};
static int GF[32][3], nGF;           /* full monoid */
static int G2[32][3], nG2;           /* depth-2 set */
static int W[6] = {1,3,9,27,81,243};
static int TR[256][6], TGT[256];
static unsigned char KFULL[256], K2[256];

static void addmap(int g[][3], int *n, int a,int b,int c){
    for(int i=0;i<*n;i++) if(g[i][0]==a&&g[i][1]==b&&g[i][2]==c) return;
    g[*n][0]=a;g[*n][1]=b;g[*n][2]=c;(*n)++;
}
static void build_sets(void){
    nGF=0;nG2=0;
    /* depth 1 and 2 */
    int cur[32][3],nc=0;
    for(int d=0;d<3;d++){ addmap(cur,&nc,M[d][0],M[d][1],M[d][2]); }
    for(int d1=0;d1<3;d1++)for(int d2=0;d2<3;d2++)
        addmap(G2,&nG2,M[d2][M[d1][0]],M[d2][M[d1][1]],M[d2][M[d1][2]]);
    /* full monoid: close under left multiplication */
    for(int i=0;i<nc;i++) addmap(GF,&nGF,cur[i][0],cur[i][1],cur[i][2]);
    int changed=1;
    while(changed){changed=0;
        int n0=nGF;
        for(int i=0;i<n0;i++)for(int d=0;d<3;d++){
            int a=M[d][GF[i][0]],b=M[d][GF[i][1]],c=M[d][GF[i][2]];
            int before=nGF; addmap(GF,&nGF,a,b,c); if(nGF!=before) changed=1;}
    }
    /* K sets: K = sum_{i=6..9} g_i(0)*3^i mod 256 */
    int hw[4]={217,139,161,227};
    memset(KFULL,0,256); memset(K2,0,256);
    int vf[3]={0,0,0}, v2[3]={0,0,0};
    for(int i=0;i<nGF;i++) vf[GF[i][0]]=1;
    for(int i=0;i<nG2;i++) v2[G2[i][0]]=1;
    for(int a=0;a<3;a++)for(int b=0;b<3;b++)for(int c=0;c<3;c++)for(int d=0;d<3;d++){
        if(vf[a]&&vf[b]&&vf[c]&&vf[d]) KFULL[(a*hw[0]+b*hw[1]+c*hw[2]+d*hw[3])&255]=1;
        if(v2[a]&&v2[b]&&v2[c]&&v2[d]) K2[(a*hw[0]+b*hw[1]+c*hw[2]+d*hw[3])&255]=1;
    }
    /* FULL is meant as a ceiling: let K be entirely free there. */
    memset(KFULL,1,256);
}

/* max hits of the straight-line family over the given subset */
static int members[256], nmem;
static int G[32][3], nG; static unsigned char *KOK;
static int s_acc[256];
static int freepos[6], nfree;
static int best_sub;

static void rec(int level){
    if(level==nfree){
        static int hist[256];
        memset(hist,0,sizeof hist);
        for(int t=0;t<nmem;t++){
            int b=members[t];
            int need=(TGT[b]-s_acc[t])&255;
            hist[need]++;
        }
        for(int k=0;k<256;k++) if(KOK[k]&&hist[k]>best_sub) best_sub=hist[k];
        return;
    }
    int i=freepos[level];
    int save[256];
    memcpy(save,s_acc,nmem*sizeof(int));
    for(int g=0;g<nG;g++){
        for(int t=0;t<nmem;t++){int b=members[t]; s_acc[t]=save[t]+G[g][TR[b][i]]*W[i];}
        rec(level+1);
    }
    memcpy(s_acc,save,nmem*sizeof(int));
}

static int best_on(int *sub,int n,int *fixed /*bitmask of constant positions*/){
    nmem=n; memcpy(members,sub,n*sizeof(int));
    nfree=0; for(int i=0;i<6;i++) if(!((*fixed>>i)&1)) freepos[nfree++]=i;
    memset(s_acc,0,sizeof s_acc);
    best_sub=0; rec(0); return best_sub;
}

int main(void){
    build_sets();
    for(int b=0;b<256;b++){int v=b;for(int i=0;i<6;i++){TR[b][i]=v%3;v/=3;} TGT[b]=b^0x51;}
    printf("|full monoid| = %d   |M_2| = %d   |K_2| = ",nGF,nG2);
    int c=0; for(int i=0;i<256;i++) c+=K2[i]; printf("%d\n\n",c);

    for(int mode=0;mode<2;mode++){
        if(mode==0){ memcpy(G,GF,sizeof GF); nG=nGF; KOK=KFULL; printf("=== FULL monoid, K free (ceiling for any depth) ===\n"); }
        else       { memcpy(G,G2,sizeof G2); nG=nG2; KOK=K2;    printf("\n=== depth-2 maps, depth-2 constants (two-layer tail) ===\n"); }

        /* no split: reproduce the branchless number */
        int all[256]; for(int b=0;b<256;b++) all[b]=b;
        int fx=0;
        if(mode==1) printf("no split                : %d\n", best_on(all,256,&fx));
        else        printf("no split                : 34 (prior art: research/cov32/family_ceiling.py, exhaustive)\n");

        /* 3-way split on trit j */
        for(int j=0;j<6;j++){
            int tot=0;
            for(int t=0;t<3;t++){
                int sub[256],n=0;
                for(int b=0;b<256;b++) if(TR[b][j]==t) sub[n++]=b;
                if(!n) continue;
                int f=1<<j; tot+=best_on(sub,n,&f);
            }
            printf("3-way on trit %d          : %d\n", j, tot); fflush(stdout);
        }
        /* 9-way split on trits j,k */
        for(int j=0;j<6;j++)for(int k=j+1;k<6;k++){
            int tot=0;
            for(int t=0;t<3;t++)for(int u=0;u<3;u++){
                int sub[256],n=0;
                for(int b=0;b<256;b++) if(TR[b][j]==t&&TR[b][k]==u) sub[n++]=b;
                if(!n) continue;
                int f=(1<<j)|(1<<k); tot+=best_on(sub,n,&f);
            }
            printf("9-way on trits %d,%d       : %d\n", j,k, tot); fflush(stdout);
        }
        fflush(stdout);
    }
    return 0;
}
